### ISSUE TITLE
[BUG] Iroha fails to start on MacOS M1 using Docker Compose single dev

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha#3451] opened 2023-05-04 07:19 UTC
### OS and Environment

MacOS M1, Docker Hub

### GIT commit hash

b1855454

### Minimum working example / Steps to reproduce

`docker compose -f docker-compose.dev.single.yml up -d`

### Actual result

The process fails with an error related to loading metadata for the archlinux:base-devel image.
```
[+] Running 0/1
 ⠿ iroha0 Warning                                                                                                                                                                     2.6s
[+] Building 2.3s (4/4) FINISHED                                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                                                  0.1s
 => => transferring dockerfile: 1.55kB                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                     0.0s
 => => transferring context: 58B                                                                                                                                                      0.0s
 => CANCELED [internal] load metadata for docker.io/library/alpine:3.16                                                                                                               2.2s
 => ERROR [internal] load metadata for docker.io/library/archlinux:base-devel                                                                                                         2.1s
------
 > [internal] load metadata for docker.io/library/archlinux:base-devel:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:e8fdfe665a3e6afae775a83db1a518a0fd4f2cc0fd947aefc6a7479cbde65bd7: not found
```

### Expected result

Iroha 2 should start successfully using Docker Compose on MacOS M1.

### Who can help to reproduce?

@astrokov7

### Notes

It seems that the archlinux:base-devel image is not compatible with the M1 platform. Consider switching to a compatible image, such as arm64v8/archlinux:base-devel, or using a multi-architecture image

**Comment by mversic** [comment] 2023-05-04 07:54
possible duplicate of #2690
please close it if so

**Closed** 2023-08-05 11:59 UTC
Labels: Bug, iroha2, Dev defect, QA-confirmed
