### ISSUE TITLE
🦟 [BUG] iroha-cli is not working with private/public keypairs

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#2520] opened 2022-07-22 13:21 UTC
### GIT commit hash

[`0d22d117`](https://github.com/hyperledger/iroha/commit/0d22d117)

### Minimum working example

```
@trace
def create_domain():
    commands = [
        iroha.command('CreateDomain', domain_id='test', default_role='user')
    ]

    tx = IrohaCrypto.sign_transaction(iroha.transaction(commands), ADMIN_PRIVATE_KEY)
    send_transaction_and_print_status(tx)
```

Context: `ADMIN_PRIVATE_KEY` is the 128 byte key generated by Python script.

### Expected behaviour

A new domain should be created.

### Actual behaviour

A new domain is not created. Instead, a log message appears:

```
Transaction hash = b'105b3595081547f208eaf4a74f1494f25674037e6961b54633aeb1d8781aa9a1', creator = admin@sos
('ENOUGH_SIGNATURES_COLLECTED', 9, 0)
('STATEFUL_VALIDATION_FAILED', 2, 1)
('REJECTED', 4, 0)
```

### Operating system

Debian 5.10.113-1, kernel 5.10.0-14-amd64

### LibC type and version

Debian GLIBC 2.31-13+deb11u3

### Current environment

Source code build

**Comment by baziorek** [comment] 2022-07-22 14:18
@6r1d Note, that the issue is somehow connected with this year HL mentorship program:
https://wiki.hyperledger.org/display/INTERN/Implement+iroha-cpp+library+for+Hyperledger+Iroha+1

But changes in iroha-cli, according to the plan would come in November.

**Comment by funkytorino** [comment] 2022-07-23 01:31
Update on this issue:
The [provided Python example](https://iroha.readthedocs.io/en/develop/getting_started/python-guide.html#sending-transactions-with-python-library) uses a serialized private key, but that only works whit Iroha's native SHA-3 provider. Attempting to use URSA and it's SHA-2 serialized private keys fails, causing Irohad to reject transaction with the shown error.

Solution for this is to recreate the private_key object, unserializing the key with something like:
`PRIVATE_KEY = ed25519_sha2.SigningKey([HEX serialized key], encoder=encoding.HexEncoder)`

After changing Python client like commented above, transactions succeeds, as expected:

Transaction hash = b'c132ba5a4b3f1d5c5d1c6a2157a861a2b0e60eb45c1834159a4fc766228e77be', creator = admin@sos
('ENOUGH_SIGNATURES_COLLECTED', 9, 0)
('STATEFUL_VALIDATION_SUCCESS', 3, 0)
('COMMITTED', 5, 0)

I guess this issue could be resolved and closed.

**Closed** 2023-02-10 11:46 UTC
Labels: Bug, 1.5
