### ISSUE TITLE
[refactor] Replace `Trap` with `panic` in `core/wasm`

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3555] opened 2023-06-01 15:53 UTC
This things works on the same way so we decided to replace all returns of `Trap`s with `panic`

Originally suggested by @mversic in #3477

**Comment by VAmuzing** [comment] 2023-11-08 00:10
Seems like the issue is no longer relevant after latest refactors.
@mversic please close the issue if you agree.

**Closed** 2023-11-08 00:11 UTC
Labels: good first issue, iroha2, Refactor
