### ISSUE TITLE
Consider introducing limit for long queries

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3379] opened 2023-04-14 10:31 UTC
@arndey suggested to intorduce the limit feature, so that there will be a way to limit execution of long queries (i.e. `FindAllAssets` requires 3 nested loops).

@appetrosyan , suggested to use lazy evaluation, wsv clonning and paggination to implement this.

**Comment by mversic** [comment] 2023-04-18 08:12
possible duplicate of #3347

**Comment by appetrosyan** [comment] 2023-05-10 10:35
One potential solution is to introduce re-entrant pagination and default to returning a reasonably paginated lazily evaluated result.

**Comment by Mingela** [comment] 2023-05-23 10:36
Agree to solve that implementing a pagination and close this one in favor of that one

**Closed** 2024-07-03 08:00 UTC
Labels: Enhancement, iroha2-dev
