### ISSUE TITLE
Fix benchmarks

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2225] opened 2022-05-18 09:45 UTC
## MWE

run 

```
cargo bench
```

## Expected

Works

## Actual 

Error messages in logs complaining about not being able to find `alice@1@wonderland`.

**Comment by s8sato** [comment] 2022-06-02 12:08
Disambiguation.
If this issue refers to WARN logs such as below on running `cargo bench --bench tps-dev`, then #2078 is responsible for it. This occurs when the `interval_us_per_tx` configuration is too short.

![image](https://user-images.githubusercontent.com/49983831/171624756-9d836e7d-f7fc-4ebf-adbd-0d951f469575.png)
![image](https://user-images.githubusercontent.com/49983831/171624773-5773425e-aa78-4f98-bac6-a1345b6a64e1.png)

Apart from that, I found another issue by accident. The `tps-dev` benchmark seems to have broken at some point since #1963. As of efa9a35692a949707ae0752119e4c4a1a08342a1, it fails with
```
thread 'main' panicked at 'The block is not yet in WSV. Need more sleep?', client/benches/tps/lib.rs:94:22
```
message, which would not be resolved by increasing [the sleep](https://github.com/hyperledger/iroha/blob/efa9a35692a949707ae0752119e4c4a1a08342a1/client/benches/tps/lib.rs#L80) (at least in 32 seconds, I've confirmed). This means the same number of blocks as the configuration are never applied to WSV. One possible cause is that the event counters are detecting more events than the actual number of blocks committed, and exiting prematurely

**Comment by s8sato** [comment] 2022-06-02 13:01
I think so too. Created #2310

**Comment by SamHSmith** [comment] 2022-07-28 09:55
I believe this is actually a consensus issue. It is probably the case that sumeragi currently can't handle high load due to some bug. This bug is however only triggered during the benchmark since it is the only time sumeragi is put under high tx load.

**Comment by appetrosyan** [comment] 2022-07-31 21:24
Related #2078

**Comment by SamHSmith** [comment] 2022-10-03 14:54
This issue no longer happens and so it can be closed.

**Closed by SamHSmith** 2022-10-03 14:54 UTC
Labels: Bug, good first issue, iroha2
