### ISSUE TITLE
[suggestion] Lightweight way to get amount of entities

### ISSUE THREAD

**Issue by Mingela** [hyperledger/iroha#4092] opened 2023-11-28 09:27 UTC
### Feature request

Currently there is no way to get an amount of entities for a query. There are no explicit queries like `getEntityCount(filter)` either.

### Motivation

Querying values like `count` is pretty standard for a storage, which is one of the use cases for Iroha. Implementing this on the client side may be too resource consumptive (for both client and Iroha).
Introducing explicit count-queries or expanding the existing way the cursor/paging is implemented with an additional attribute `count` to determine how many entries there are is requested. Other options are welcome as well.

### Who can help?

@mversic

**Comment by Erigara** [comment] 2024-10-01 08:07
@DCNick3 should we close this?

**Comment by DCNick3** [comment] 2024-10-01 08:34
Yeah, this is dupe of #4984, implemented in #5016

**Closed by DCNick3** 2024-10-01 08:34 UTC
Labels: Enhancement, iroha2-dev, api-changes
