### ISSUE TITLE
can't build android-build.sh

### ISSUE THREAD

**Issue by Bo3o2S** [hyperledger/iroha#1684] opened 2018-08-28 01:10 UTC
![image](https://user-images.githubusercontent.com/14229134/44694710-177c8980-aaaa-11e8-860b-6dff33437b20.png)

when i built android-build.sh with ndk-r17b
it display some error. but what's wrong with it??
i tried to like this

**OS : ubuntu 16.04 64bit
command : ./android-build.sh x86 15 /home/lee/Downloads/android-ndk-r17b jp.co.soramitsu.iroha.android Release**

**Comment by igor-egorov** [comment] 2018-08-29 11:43
Hi @Bo3o2S 
Thanks for submitting the issue!
Most likely that the problem is caused by using the deprecated NDK GCC 4.9 toolchain. The fix is to switch to NDK clang toolchain. We will update our repo soon.

To build the library please apply the patch to your `android-build.sh` script:
```
diff --git a/shared_model/packages/android/android-build.sh b/shared_model/packages/android/android-build.sh
index 6a3b6783b..227cb26a5 100755
--- a/shared_model/packages/android/android-build.sh
+++ b/shared_model/packages/android/android-build.sh
@@ -55,7 +55,7 @@ else
     exit 1
 fi
 
-ANDROID_TOOLCHAIN_ARGS=(-DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION="$VERSION" -DCMAKE_ANDROID_ARCH_ABI="$PLATFORM" -DANDROID_NDK="$NDK_PATH" -DCMAKE_ANDROID_STL_TYPE=c++_static)
+ANDROID_TOOLCHAIN_ARGS=(-DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang -DANDROID_TOOLCHAIN=clang -DNDK_TOOLCHAIN_VERSION=clang -DCMAKE_SYSTEM_VERSION="$VERSION" -DCMAKE_ANDROID_ARCH_ABI="$PLATFORM" -DANDROID_NDK="$NDK_PATH" -DCMAKE_ANDROID_STL_TYPE=c++_static)
 DEPS_DIR="$PWD"/iroha/dependencies
 INSTALL_ARGS=(-DCMAKE_INSTALL_PREFIX="$DEPS_DIR")
 

```

The patch adds the following variables to `ANDROID_TOOLCHAIN_ARGS`:
```
-DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang -DANDROID_TOOLCHAIN=clang -DNDK_TOOLCHAIN_VERSION=clang
```

Please let me know if the issue is still present.

**Comment by Bo3o2S** [comment] 2018-08-30 14:47
it's working now and copile and link successfully
but when i tried to run sample app with linked library, it cannot find "rand" function

![image](https://user-images.githubusercontent.com/14229134/44859387-fc2e9b80-acae-11e8-86c1-ccef28bf8c6d.png)

**Comment by Warchant** [comment] 2018-09-06 15:58
@Bo3o2S please share here the output of 

**Linux**:
```
ldd libirohajava.so
```

**MAC**:
```
otool -L libirohajava.jnilib
```

**Comment by Bo3o2S** [comment] 2018-09-07 05:31
**OS : ubuntu 16.04 64 bit
command : ldd libirohajava.so**

![image](https://user-images.githubusercontent.com/14229134/45200207-aeb3bf00-b2aa-11e8-8a3d-39e5f0934518.png)

**Comment by Warchant** [comment] 2018-09-07 14:09
@Bo3o2S something is wrong with your `.so` file. Try to rebuild it.

**Comment by Bo3o2S** [comment] 2018-09-11 00:45
i tried to build 5times but it's not different.
i just change ANDROID_TOOLCAHIN_ARGS "igor-egorov" suggest in android-build.sh. 
and i can build but when i entered the command "ldd libirohajava.so", it still appears "not a dynamic executable"

i change ANDROID_TOOLCHAIN_ARGS like this
 
**ANDROID_TOOLCHAIN_ARGS=(-DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang -DANDROID_TOOLCHAIN=clang -DNDK_TOOLCHAIN_VERSION=clang -DCMAKE_SYSTEM_VERSION="$VERSION" -DCMAKE_ANDROID_ARCH_ABI="$PLATFORM" -DANDROID_NDK="$NDK_PATH" -DCMAKE_ANDROID_STL_TYPE=c++_static)
DEPS_DIR="$PWD"/iroha/dependencies
INSTALL_ARGS=(-DCMAKE_INSTALL_PREFIX="$DEPS_DIR")**

what's wrong with it?

**Comment by LiraLemur** [comment] 2019-01-17 09:42
Please try new library: https://github.com/Warchant/iroha-pure-java - if any difficulties remain let us know in the chat: https://chat.hyperledger.org/channel/iroha

Since the version in the issue is old, I suggest closing the issue.

**Closed** 2019-01-19 18:34 UTC
Labels: SDK, infrastructure
