### ISSUE TITLE
[BUG] cargo build -p iroha_client_cli fails field Error: Failed to check the smartcontract at path: 

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha#3447] opened 2023-05-03 14:10 UTC
### OS and Environment

Docker Hub, MacOS 13.3 Ventura

### GIT commit hash

6daae999

### Minimum working example / Steps to reproduce

docker pull --platform x86_64 hyperledger/iroha2:dev
docker-compose -f docker-compose.dev.yml up -d
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
cargo build -p iroha_client_cli

### Actual result

   Compiling iroha_telemetry v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/telemetry)
   Compiling iroha_client_cli v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/client_cli)
error: failed to run custom build command for `iroha_client v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/client)`

Caused by:
  process didn't exit successfully: `/Users/michaeltimofeev/Documents/soramitsu/iroha/target/debug/build/iroha_client-8e10dcd7037f731f/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=tests/integration/smartcontracts

  --- stderr
  Error: Failed to check the smartcontract at path: /Users/michaeltimofeev/Documents/soramitsu/iroha/client/tests/integration/smartcontracts

### Expected result

build successful 

### Who can help to reproduce?

@timofeevmd

**Comment by ffakenz** [comment] 2023-09-04 19:19
# Error Report: cargo check error while building the Iroha2 client_cli Development Environment

## Summary
Encountered a fatal cargo check error while running cargo to build the Iroha2 client_cli development environment on a x86_64-apple-darwin arch.

## Steps to Reproduce
1. Clone the Iroha repository from https://github.com/hyperledger/iroha
2. Switch to the iroha2-dev branch
3. Run the following command:
bash cargo build -p iroha_client_cli
## System Configuration
- *arch*: x86_64-apple-darwin

## Error Details

### Error Message:
error: failed to run custom build command for `iroha_client v2.0.0-pre-rc.19 (/Users/lambda/Documents/repos/iroha/client)`

Caused by:
  process didn't exit successfully: `/Users/lambda/Documents/repos/iroha/target/debug/build/iroha_client-a45f1a5d224da1af/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=tests/integration/smartcontracts

  --- stderr
  Error: Failed to check the smartcontract at path: /Users/lambda/Documents/repos/iroha/client/tests/integration/smartcontracts

  Caused by:
      `cargo check` returned non zero exit code (exit status: 101). Stderr:
      error: "/Users/lambda/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
              rustup component add rust-src --toolchain nightly-2023-06-25-x86_64-apple-darwin

  Location:
      wasm_builder/src/lib.rs:414:9

### Notes:
- the error remains even after running the following commands:
rustup toolchain install nightly-2023-06-25

rustup component add rust-src --toolchain nightly-2023-06-25-x86_64-apple-darwin

**Comment by mversic** [comment] 2023-09-05 05:15
the issue can be mitigated if you build the whole project from the root

**Comment by mversic** [comment] 2023-09-22 07:10
duplicate of #3311

**Closed by mversic** 2023-09-22 07:10 UTC
Labels: Bug, iroha2, Dev defect, QA-confirmed
