### ISSUE TITLE
Add primary key to account

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2085] opened 2022-04-12 07:42 UTC
Refactor the accounts to only *optionally* have an alias. 

We still need to retain the current semantics of account structure, but most data should be stored in a separate location: hash-table keyed by the account's ss58 (or pub_key) address, which contains actual data, an account alias is only an interface to all of that.

**Comment by mversic** [comment] 2024-01-24 11:17
relevant [RFC](https://wiki.hyperledger.org/display/iroha/Key-centric+accounts+structure)

**Comment by s8sato** [comment] 2024-02-21 07:52
### My plan

- Make `AccountId` some string derived from the account signatories
  - Stay consistent with shared wallets (accounts such that `1 < account.signatories.len()`)
  - Refactor the data access flow as `AccountId` lost `DomainId`
  - Absorb any other impacts

#### Out of scope

The following is left to other issues:

- From [ADR](https://wiki.hyperledger.org/display/iroha/Key-centric+accounts+structure)
  - Account alias
  - Primary and second keys
  - Account archival
  - Key versioning
- Other concerns
  - Any functionalities other than as an identifier
  - Discussion on appropriate size of ID

### Why is this change necessary?

- Collision resistance for offline account creation
- Centralize user identities
  - Currently "name@domain" or public key, depending on the situation

#### Pros

- Rare collisions between newly requested and the existing IDs
  - Offline account creation will be feasible
- One less step to create account
  - Users don't have to come up with their own names
- Possibility of utilizing namespaces other than strings derived from public keys
  - If non-user accounts are introduced due to implementation needs

#### Cons

- Signatories change involves account ID change
  - Some blockchains have signatories immutable. What about Iroha?
- Not easy strings for users to remember and induce input errors
  - In any case, the string should have a checksum or require some confirmation before transaction execution
- No special use other than as an identifier
  - For now

<details> <summary>Decision log</summary>

#### Decision log

TODO

</details>

**Comment by mversic** [comment] 2024-02-21 08:07
> Refactor the data access flow as `AccountId` lost `DomainId`

Do we necessarily have to exclude `DomainId`? how do we absorb this impact because we have accounts as part of domain

>  Account alias

I think we need this

> Primary and second keys

so every account will have to have a unique primary key, but secondary keys can be used by multiple accounts

> Account archival

we can leave this for later

> Key versioning

what is meant by this?

**Comment by mversic** [comment] 2024-02-21 08:21
> > Make AccountId some string derived from the account signatories
> 
> does it have to be derived? it can be any string set by the user, but when setting it we have to make sure it's unique in the blockchain

obviously in this case offline creation can fail if user sets a non-unique account alias

**Comment by s8sato** [comment] 2024-02-21 16:21
Added the __Record of my thoughts__ section to the bottom of https://github.com/hyperledger/iroha/issues/2085#issuecomment-1956071335
I'd appreciate if anyone reviews as I don't think I have a solid vision at the moment

**Comment by Mingela** [comment] 2024-02-22 10:55
So, implicitly an account is going to be identified by it's public key unless an optional alias (`name@domain`) is introduced, right? Whereas public key formatted aliases should be prohibited?
Introducing the requirement that key pairs (at least ones which are used for a primary key) have to be unique.

Consequently I've got some further questions:
* What if two accounts get created offline using the same key pair, what's the collision resolution here? Actually how can we distinct them? 
* Can an account have multiple aliases? 
* Can an account drop or change an alias? 
* Can an account set an alias used by someone else in the past?

**Comment by mversic** [comment] 2024-02-27 08:06
> What if two accounts get created offline using the same key pair, what's the collision resolution here? Actually how can we distinct them?

we consider this so improbable that for all intents and purposes is impossible

> Can an account have multiple aliases?

I'd prefer not

> Can an account drop or change an alias?

I'd say no, let's keep it simple. User can only define an alias when registering account.

> Can an account set an alias used by someone else in the past?

yes

**Comment by Mingela** [comment] 2024-02-27 08:19
> > Can an account set an alias used by someone else in the past?
> 
> yes

Seems all entities referencing an account must rely on the key based identification exclusively though (assets, permission tokens, maybe smth else) to prevent unregistering + registering with same alias kind of 'attack'. Alternatively, aliases might be made exclusive no matter whether the associated account is unregistered or not (which does not seem memory effective though).


> > Can an account drop or change an alias?
> 
> I'd say no, let's keep it simple. User can only define an alias when registering account.

If that's optional I guess we still should allow an account to set that after registering, right?


The other question is how an account is going to be addressed 'by default' (alias alternative), just the primary public key?

**Comment by mversic** [comment] 2024-02-27 08:53
> Seems all entities referencing an account must rely on the key based identification exclusively though (assets, permission tokens, maybe smth else) to prevent unregistering + registering with same alias kind of 'attack'. Alternatively, aliases might be made exclusive no matter whether the associated account is unregistered or not (which does not seem memory effective though).

if that is a problem, then that is a problem even with the current accounts, no? We've had a similar problem with permission tokens. I've opened #4329 for this

> If that's optional I guess we still should allow an account to set that after registering, right?

why? it's optional but you have to decide at the time of registering whether or not to set an alias. If that is really required we can always add that functionality. To keep it simple let's just allow defining aliases at the time of registering

**Comment by Mingela** [comment] 2024-02-27 08:58
> > Seems all entities referencing an account must rely on the key based identification exclusively though (assets, permission tokens, maybe smth else) to prevent unregistering + registering with same alias kind of 'attack'. Alternatively, aliases might be made exclusive no matter whether the associated account is unregistered or not (which does not seem memory effective though).
> 
> if that is a problem, then that is a problem even with the current accounts, no? We've had a similar problem with permission tokens. I've opened #4329 for this

right, seems so even now, though I was rather referring to a scenario of taking over an asset or entity ownership (apparently) via registering an account with the alias used by the initial account

> > If that's optional I guess we still should allow an account to set that after registering, right?
> 
> why? it's optional but you have to decide at the time of registering whether or not to set an alias. If that is really required we can always add that functionality. To keep it simple let's just allow defining aliases at the time of registering

agree

**Comment by s8sato** [comment] 2024-02-27 18:44
### What difference does each ID specification make?

| Account ID format | `name@domain` (ND) | [`keyshash`](#keyshash) (K) | `keyshash@domain` (KD) | [`uuid`](#uuid) (U) |
| -- | -- | -- | -- | -- |
| [User input in new account request](#user-input-in-new-account-request) | `name` `domain` | `domain` | `domain` | `domain` |
| Collision check in new account request | <ul><li>by `name@domain`</li></ul> | <ul><li>ignore?</li><li>by `keyshash` ?</li></ul> | <ul><li>ignore?</li><li>[by `keyshash` ?](#kd-collides-by-k)</li><li>[by `keyshash@domain` ?](#kd-collides-by-kd)</li></ul> | <ul><li>ignore?</li><li>by `uuid` ?</li></ul> |
| [User input in specifying transfer destination](#user-input-in-specifying-transfer-destination) | <ul><li>`name@domain`</li><li>alias `another@domain`</li></ul> | <ul><li>`keyshash`</li><li>alias `name@domain`</li></ul> | <ul><li>depends on identity boundary. same issue as collision check</li><li>alias `name@domain`</li></ul> | <ul><li>`uuid`</li><li>alias `name@domain`</li></ul> |
| Complementary namespace | none | available | [available](#complementary-namespace-of-kds) | none |
| Aliases | interfere with ID space |  | interfere with ID space |  |
| [Add alias](#alias-creation-and-update) | feasible but namespace consumptive | feasible | feasible but can intentionally block new accounts | feasible |
| [Modify alias](#alias-creation-and-update) | feasible | feasible | feasible but can intentionally block new accounts | feasible |
| Remove alias | not for primary one | feasible | feasible | feasible |
| Impacts |  |  |  |  |
| Impacts to existing codebase| - | <ul><li>domain ID outside account ID</li><li>account ID change with signatories change?</li></ul> | <ul><li>account ID change with signatories change?</li></ul> | <ul><li>domain ID outside account ID</li></ul> |


#### Annotations

##### `keyshash`

- A string or number derived from the account signatories (public keys) by hash-like function
  - Something like `0x01..cDeF` or `BasE58strinG`

##### `uuid`

- UUID as an account ID suggested in [ADR] would be still feasible as long as it is coupled with the account signatories

##### User input in new account request

- Assuming keys are configured in the client

##### KD collides by K

- This means an user (group) is not allowed to use the same key(s) in different domains

##### KD collides by KD

- This means `k@d1` and `k@d2` are both valid accounts that share the keys. I'm not sure if this is safe situation. One thing I can tell is this will be less strict than having K collide by K:
  - Even if there is an unintended collision at the K level, it will not be noticed. `k@d1` can arbitrarily act as `k@d2` just by faking the last character

##### User input in specifying transfer destination

- In any case, checksum or some prompt and confirmation would be desired to prevent input errors

##### Complementary namespace of KDs

- If utilized for system accounts, what will be the representation of domain-free system accounts?

##### Alias creation and update

- would be bound to the `domain`

**Comment by s8sato** [comment] 2024-02-27 18:49
Included aliases in the scope of this issue as it seems to be inseparable from the initial restructural change.

### Replies to comments

@mversic

#### 1. Need to exclude domain ID?

This question brought insight. See "K" and "KD" comparison in the table

#### 2. Impacts of account ID without domain ID?

The basic idea to absorb those impacts would be to consider the data access flow separately from the organizational chart.

for example:

- All identifiable entities are stored as key-value pairs flatten in the world state
  - Those entities have referential IDs of other entities

```
- wsv.domains: Map<DomainId, Domain>
  - domain.accounts: Set<AccountId>
  - domain.assets: Set<AssetId>
- wsv.accounts: Map<AccountId, Account>
  - account.domain: DomainId
  - account.assets: Set<AssetId>
  - account.portfolio: Map<AssetId, Balance>
- wsv.assets: Map<AssetId, Asset>
  - asset.domain: DomainId
  - asset.distribution: Map<AccountId, Balance>
```

where:
- `EntityId` and `Entity` here are the current `Entity` divided into `id` and other fields
- `Asset` here is a consolidation of the current `Asset` and `AssetDefinition`
- Mutable APIs must be carefully implemented to maintain consistent relationships between entities

#### 3. Primary and secondary keys?

I have no idea about secondary keys at the moment.
If only for the purpose of mitigating the risk of key theft, another small change might work:
introduce "m of n" signature check condition and set it as the authentication policy for personal accounts

#### 4. Is uniqueness enough?

Yeah, that's exactly why I'm cautious about this change.
I think this question comes down to a comparison of K and U.
If there was a motive to K, it would be about the space that cannot be derived from keys 

@Mingela

#### 5. Identified by keys unless has aliases?

In the user interface, that will be true.
In the chain, on the other hand, since aliases are supposed to resolve to IDs on the chain surface, accounts will be identified by IDs (essentially keys in K case) regardless of aliases.
If backwards compatibility in the user interface is a concern, aliases are optional for new accounts but required for existing accounts

#### 6. Deny aliases of KD format?

Yeah, KD-format ID and KD-format alias will never be distinguished.
This means a situation where aliases block new accounts.
Maybe KD-format IDs should be rejected?

#### 7. Same key for different IDs?

See [KD collides by KD](#kd-collides-by-kd)

#### 8. Multiple aliases?

Feasible. Aliases are optional, which means they are mapped to IDs internally

#### 9. Remove or modify aliases?

Feasible. Keys of the alias-to-id map will be checked if they collide

#### 10. Alias transfer, or hijacking?

An alias released by someone else can be retrieved at the next block time.
But I don't think something like a takeover would happen.
Since alias is supposed to be resolve to ID on the chain surface, alias modification would not affect the relationship between entities linked by IDs.
Any query or transaction cannot target the previous holder of the alias because the world state forgets it.
On the chain, no one can act as someone else without stealing the private key, regardless of aliases.
So if there is a problem, it will happen outside the chain.
For example, if an alias acts as an address in the UI, there may be cases where the alias change is not well known to the parties involved, an invalid or transferred alias could be specified as the destination and the asset could be lost.
I can't think of a good solution, but at least this will be not a flaw in the alias specification

**Comment by Mingela** [comment] 2024-02-28 09:45
@s8sato 

* I really would like an account to be referenceable in a static way, if we don't introduce a primary key which would be the only argument of K's `keyhash` function result (may be even just the public key), I'd rather support UUIDs. To elaborate, we'd just need `Map<String, AccountId>` to resolve aliases to `AccountId` (which are UUIDs in this case), preferably aliases still could be in the `name@domain` format
* Generally a domain inclusion to an account id becomes unnecessary unless we define a domain being the uniqueness scope for primary keys

**Comment by s8sato** [comment] 2024-03-06 10:30
[the original requirements]: https://github.com/hyperledger/iroha/issues/1594#issue-1048402600
[my own comment]: https://gist.github.com/s8sato/058d4335ba9219a8456bdd09518178b1#uuid

After reviewing [the original requirements], I found the new account IDs required more than just uniqueness.
Let me refute [my own comment]:

> UUID as an account ID suggested in ADR would be still feasible as long as it is coupled with the account signatories

The problem is that for such account that do not require registration, there is no clue to the "account signatories" other than its ID (address)

### Role of `AccountId` in authentication

Let’s look back at the current transaction authentication:

```rust
// outside chain
- transaction
    - payload
        - authority: AccountId  // 1. authenticator fetches `authority` which the transaction senders claim to have
    - signatures                // 4. authenticator verifies `signatures` with `signatories`
// inside chain
- account
    - id: AccountId             // 2. authenticator finds the account matched with `authority`
    - signatories: [PublicKey]  // 3. authenticator decides who should sign the transaction
    - signature_check_condition
```

And we are trying to realize the following scenario:

1. Bob creates an account offline, obtains an ID (address), and asks Alice to send assets to the address
2. Alice sends assets to Bob, who is not yet on the chain. This transfer is valid and Bob's account is created from ID (address) only
3. Bob sends a transaction with himself as the authority

The situation at this time, assuming no additional fields, is as follows:

```rust
// outside chain
- transaction
    - payload
        - authority: AccountId  // 1. authenticator fetches `authority` which the transaction senders claim to have
    - signatures                // 3. authenticator verifies `signatures` with `account.id`
// inside chain                                                                 ^^^^^^^^^^
- account
    - id: AccountId             // 2. authenticator finds the account matched with `authority`
    // - signatories: []
    - signature_check_condition
```

If we continue to follow the design where multi-signature transactions directly target multi-signatory accounts, we would fall into one of the following:

- Have `AccountId` fully contains `signatories: [PublicKey]`
- Add `transaction.payload.signatories` field:

    <details><summary>signatories in transaction</summary>

    ```rust
    // outside chain
    - transaction
        - payload
            - authority: KeysHash as AccountId  // 1. authenticator fetches `authority` which the transaction senders claim to have
            - signatories: [PublicKey]          // 2. authenticator checks if `authority` is derived from `signatories`
        - signatures                            // 4. authenticator verifies `signatures` with `signatories`
    // inside chain
    - account
        - id: KeysHash as AccountId             // 3. authenticator finds the account matched with `authority`
        // - signatories: []
        - signature_check_condition
    ```

    </details>

However, I think a better way would be to prevent transactions from directly targeting shared accounts.
In this case, transactions would have single signature.
Also, `AccountId` can simply be the same representation as `PublicKey`:

```rust
// outside chain
- transaction
    - payload
        - authority: PublicKey as AccountId     // 1. authenticator fetches `authority` which the transaction senders claim to have
    - signature                                 // 2. authenticator verifies `signature` with `authority`
// inside chain                                                                                ^^^^^^^^^
- account_personal
    - id: PublicKey as AccountId
    // - signatories: []
    // - signature_check_condition
```

Another remarkable thing here would be that transaction authentication is self-contained without reference to the chain

### Multi-signature alternatives

Thus, since a single transaction can no longer have sufficient authority over shared accounts, another method of registering and modifying shared accounts should be provided.
I think stateful triggers would be one of the solutions:

1. A proposal for a shared account is sent by one of the members:

    ```rust
    // outside chain
    - transaction
        - payload
            - authority: PublicKey as AccountId
            - instructions: [RegisterTrigger(shared_account_registerer)]
        - signature
    ```

2. The dedicated trigger for the shared account registration is registered and begins collecting signatures:

    ```rust
    // inside chain
    - shared_account_registerer
        - payload
            - id: TriggerId
            - signatories: [PublicKey]  // members of the shared account
            - signature_check_condition
            - executable                // will register the shared account
        - signatures                    // collected from signatories
    ```

3. Each member of the shared account votes on the account registration proposal:

    ```rust
    // outside chain
    - transaction
        - payload
            - authority: PublicKey as AccountId
            - instructions: [ApproveTrigger(shared_account_registerer.id, signature(shared_account_registerer.payload))]
        - signature
    ```

4. Once all necessary signatures are gathered, the trigger executes and the shared account is registered:

    ```rust
    // inside chain
    - account_shared
        - id: PublicKeyLike as AccountId
        - signatories: [PublicKey]
        - signature_check_condition
    ```

    where:
      - `PublicKeyLike` has the same representation as `PublicKey`, but indicates "system" accounts and is guaranteed to be invalid as a `PublicKey`

Instructions other than registration for shared accounts would be performed in a similar manner

**Comment by Mingela** [comment] 2024-03-06 11:10
If `shared_account_registerer` trigger is introduced why not use such approach for any multisignature transaction instead? I mean instead of registering another type of entity (`account_shared`), why not execute the target logic right away?
Example would look exactly like step 2, but instead of registering the shared account the executable would perform the 'target' logic.
Basically that means callable triggers might be defined just with custom `signature_check_condition` to represent 'multisignature' nature of an action.

**Comment by s8sato** [comment] 2024-03-06 11:42
@Mingela 

- A shared account would be registered as an entity to be allowed to hold assets and permissions.
- A shared account would be the same `Account` type as a personal account, which is the intent of `PublicKeyLike`

I think I recently [here](https://github.com/hyperledger/iroha/issues/4229#issuecomment-1958880901) suggested something close to what you are thinking of

**Comment by 0x009922** [comment] 2024-03-07 08:14
I have looked into the comments and thoughts, but don't have any comments/objections.

**Comment by s8sato** [comment] 2024-03-08 07:12
If we go forward with this, I'd like to have a more solid basis for rejecting other candidates.

For example, I suggested implementing multi-signature using triggers, but I'm not sure if that's a good way to go.
Another suggestion was collecting signatures outside the chain, perhaps like bitcoin, which would mean this feature relies on another trustful network.
One question here is, do we provide a way to handle such a situation where the representative, who has collected signatures and about to submit the multi-signature transaction, disappears despite the signature check condition is met?

### Impacts on the codebase

- `AccountId` no longer including `DomainId` entails changes in data structure and access flow
- Account signatories become immutable, or mutable involving the account ID
- Anything remarkable else?

**Comment by Mingela** [comment] 2024-03-11 12:09
I consider any valid public key to be a valid reference in a network even if that's not registered/activated yet. In a public blockchain all key pairs just 'exist' (bound to an account).

It becomes more difficult in case of:
* multisignature (shared) accounts, though we could just prohibit creating such offline or provide a way how to calculate the `PublicKeyLike` offline knowing public keys of the representatives
* private blockchain, seems a transaction targeting an account that does not exist yet should be either dropped without reject (retry later) or stored in a specific section of either/both block or/and cache and be processed only when the related account 'registers' (actually reminds me the way how a trigger gets executed on a event)

**Comment by s8sato** [comment] 2024-03-11 15:57
@Mingela 

- My understanding is both any personal `PublicKey` and any shared `PublicKeyLike` addresses are valid.
  The latter will be able to be derived at clients once all the members (`signatories: [PublicKey]`) are given, otherwise no one can propose shared account registrations
- My anticipation is two kinds of "domains" would coexist in one chain if both private and public are default features.
  In this case, such an account that does not exist yet could be considered to belong to "the public default domain", where is no authorization specific to any "private domain".
  I think this is a kind of authorization (permission validation) issue which we have not yet discussed

**Comment by mversic** [comment] 2024-03-12 06:51
@sato you said:
> Account signatories become immutable, or mutable involving the account ID

I would say that we should not support modifying of the primary key since that is part of account ID. Secondary keys can be modified

> AccountId no longer including DomainId entails changes in data structure and access flow

what's the point of having domains if accounts are no longer in domains. I think it's quite important that we keep the ability to register accounts in domains in addition to which we can also have accounts outside any domain

also:
> No special use other than as an identifier at the moment

isn't the primary key also the main signatory?

**Comment by Mingela** [comment] 2024-03-12 07:03
> > AccountId no longer including DomainId entails changes in data structure and access flow
> 
> what's the point of having domains if accounts are no longer in domains. I think it's quite important that we keep the ability to register accounts in domains in addition to which we can also have accounts outside any domain

roles could be attached to any account in a domain (aka default role of a domain) as an example, aggregation of entities by a domain seems a useful feature in general, no domain seems reasonable as well though 'no domain' is like just another domain treated specially

> > No special use other than as an identifier at the moment
> 
> isn't the primary key also the main signatory?

what does 'main' refer to exactly? isn't that determined at the level of a `signature_check_condition`?

**Comment by s8sato** [comment] 2024-03-12 07:34
@mversic 

- To be honest, as I mentioned before, I don't understand what the concept of primary and secondary keys bring. If you have any ideas please share
- I have no intention to make any changes to the entities hierarchy. Only the data access flow (where the entities and references are stored) would change
- Although I don't quite understand it, I think the primary and secondary keys (vertical inner one person) and the signatories (horizontal across persons) are orthogonal concepts
   - The concept of "main signatory" or "representative" seems to suggest a single point of failure. I think that is the very reason why we have maintained `signatories: [PublicKey]` instead of separating them into primary and secondary keys
   - Also, please note that any posts before [I noticed the authentication requirement] might be outdated

[I noticed the authentication requirement]: https://github.com/hyperledger/iroha/issues/2085#issuecomment-1980557101

**Comment by s8sato** [comment] 2024-03-12 07:35
## A short summary so far

### Changes

- `AccountId` will be some type that can be parsed to `PublicKey` or `PublicKeyLike` (which is invalid as but has the same representation as `PublicKey`)
  - `name@domain` will be an optional account alias for user interface that is resolved to `AccountId`

### Motivations

- For public blockchain use, `AccountId` should have an authentication functionality

### Implications

- `DomainId` will be dropped from `AccountId`
  - Entities hierarchy below the world will have different implementation
    - domains, asset definitions, assets
  - Any data model relevant to accounts can be involved
    - permissions, roles, events
- Multi-signature account ID will be linked to its signatories
  - never changes or changes in conjunction with its signatories
- New kind of triggers will be introduced, if elected as a multi-signature implementation

### Blocks

- PoC around `PublicKey` and `PublicKeyLike`

### Discussions

- Multi-signature implementation

**Comment by mversic** [comment] 2024-03-12 10:08
Results of the discussion: 

If we proceed with using public keys as identifiers of accounts we will do this in 3 steps:
1. Replace `account@domain` with public key as `AccountId` and don't support account aliases
2. Open a separate issue to discuss whether we want to implement alias as part of Iroha or delegate this to external service (I would prefer to keep alias resolution as a separate service outside Iroha to not complicate the codebase)
3. Open a separate issue to discuss implementation of multisig accounts

The main blocker to the decision whether or not to proceed with account restructuring is that this will require significant adjustments in the private blockchain POCs that use Iroha that we have at the moment. 

This feature doesn't seem to have benefits for private blockchains, but it also doesn't impair their functionality so I don't have anything against proceeding with it

**Comment by s8sato** [comment] 2024-03-12 10:15
I think we can close this issue as the title became a bit misleading, or rename the title and keep it as a tracking issue @mversic

**Comment by mversic** [comment] 2024-03-13 12:53
@s8sato you can proceed with the account restructuring, we are also required to keep account aliases but for the time being we can remove them and re-introduce them later after the main change

**Comment by s8sato** [comment] 2024-03-18 07:52
If there are no problems with the [PoC](https://github.com/hyperledger/iroha/pull/4371), I think we can start on the first of the following three:

- [ ] `AccountId` replacement
- [ ] https://github.com/hyperledger/iroha/issues/4372
- [ ] https://github.com/hyperledger/iroha/issues/4373

**Closed** 2024-05-15 10:54 UTC
Labels: Enhancement, iroha2-dev, Refactor
