### ISSUE TITLE
Improve versioning

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1671] opened 2021-12-03 16:25 UTC
Current Versioning has a lot of code duplication and unnecessary fluff.

**Comment by mversic** [comment] 2021-12-04 16:09
The ability to manage dependencies for all workspace crates is not yet available in `cargo`. However, here is [a tracking issue](https://github.com/rust-lang/cargo/issues/8415) for this feature. Once available we can make good use of it to manage dependency versions for all of our crates

**Comment by mversic** [comment] 2021-12-05 16:12
Duplicate of #1675

**Closed by mversic** 2021-12-05 16:12 UTC
Labels: iroha2
