### ISSUE TITLE
Grant and Revoke roles should emit `RoleGranted`/`RoleRevoked` events. 

### ISSUE THREAD

**Issue by omkar-mohanty** [hyperledger/iroha#2257] opened 2022-05-24 07:27 UTC
Following from #2007 as of now `Revoke` role (in `smartcontracts/isi/account.rs`) emits `PermissionRemoved` event which is misleading since roles are a collection of permissions. Refactor the code so that `Revoke` role emits `RoleRemoved` and `PermissionRemoved` events.

**Comment by Arjentix** [comment] 2022-12-19 10:19
Closed as duplicate of #2280

**Closed by Arjentix** 2022-12-19 10:19 UTC
Labels: iroha2
