### ISSUE TITLE
Account ID gets passed in as Asset ID when doing the Add Asset Quantity transaction

### ISSUE THREAD

**Issue by Katniss394** [hyperledger/iroha#1553] opened 2018-07-11 07:44 UTC
I'm new to Hyperledger Iroha. I just set up a network following the guide [here](https://iroha.readthedocs.io/en/latest/getting_started/) I created an asset and the transaction was successful but when I try to do the Add Asset Quantity transaction to add the newly created asset to the admin@test account and check the status, I get this message : `Transaction has not passed stateless validation. 0 AddAssetQuantity: [[Wrongly formed asset_id, passed value: 'admin@test'. Field should match regex '[a-z_0-9]{1,32}\#([a-zA-Z]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)*[a-zA-Z]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?' ]]`

Looks like the value I enter at the account id prompt is being passed in as the value for asset id.

**Comment by l4l** [comment] 2018-07-19 23:48
Thank you!
After recent fix (#1511) documentation & iroha-cli become outdated. The issue is also described in #1559, so I'm closing the issue

**Closed by l4l** 2018-07-19 23:48 UTC
