### ISSUE TITLE
Return pending transactions in batches

### ISSUE THREAD

**Issue by arndey** [hyperledger/iroha#4091] opened 2023-11-28 07:08 UTC
### Feature request

Return `BatchedResponse<Vec<SignedTransaction>>` instead of `Vec<SignedTransaction>`

### Motivation

It's hard to decode on our side without BatchedResponse

### Who can help?

@mversic

**Comment by mversic** [comment] 2023-11-28 07:45
duplicate of #4072

**Comment by VAmuzing** [comment] 2024-01-05 04:40
Closing the issue in favour of the new one #4183

**Closed by VAmuzing** 2024-01-05 04:40 UTC
Labels: Enhancement, good first issue, iroha2, api-changes
