### ISSUE TITLE
Transaction status sometimes is not sent by peer

### ISSUE THREAD

**Issue by rkharisov** [hyperledger/iroha#1492] opened 2021-09-30 09:00 UTC
Precondition: client subscribes to transaction status and as soon as peer responds with `SubscriptionAccepted` event the client sends transaction itself. 

Expected: Event with transaction status (`Committed`, `Rejected`, `Validating`) is received from peer.

Actual: No event about transaction is sent by peer

Note 1. Transaction eventually committed, just no status about it received

Note 2. Transactions are not MST

Note 3. Usually subscription is accepted by one peer, but transaction is sent to another

Note 4. This problem is raised from time to time, not with every transaction

**Comment by eadventurous** [comment] 2021-11-25 09:11
Issue closed as we could not reproduce the bug. Though we added better description and a more extensive test.

**Comment by appetrosyan** [comment] 2021-11-30 15:56
The issue seems to persist 

https://github.com/hyperledger/iroha/runs/4369233906?check_suite_focus=true

**Closed** 2021-12-02 07:46 UTC
Labels: bug, iroha2
