### ISSUE TITLE
[BUG] cargo run -p iroha_client_cli --release fails field FindPermissionTokensByAccountId

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha#3448] opened 2023-05-03 14:10 UTC
### OS and Environment

Docker Hub, MacOS 13.3 Ventura

### GIT commit hash

6daae999

### Minimum working example / Steps to reproduce

docker pull --platform x86_64 hyperledger/iroha2:dev
cargo run -p iroha_client_cli --release

### Actual result

   ```
Compiling iroha_version v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/version)
   Compiling iroha_crypto v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/crypto)
   Compiling iroha_config_base v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/config/base)
   Compiling iroha_config v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/config)
   Compiling iroha_logger v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/logger)
   Compiling iroha_futures v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/futures)
   Compiling iroha_telemetry v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/telemetry)
   Compiling iroha_client_cli v2.0.0-pre-rc.13 (/Users/michaeltimofeev/Documents/soramitsu/iroha/client_cli)
error[E0451]: field `id` of struct `iroha_data_model::prelude::FindPermissionTokensByAccountId` is private
   --> client_cli/src/main.rs:545:74
    |
545 |             let find_all_permissions = FindPermissionTokensByAccountId { id: self.id.into() };
    |                                                                          ^^^^^^^^^^^^^^^^^^ private field

For more information about this error, try `rustc --explain E0451`.
error: could not compile `iroha_client_cli` due to previous error
```

### Expected result

build successful 

### Logs in JSON format

nothing todo

### Who can help to reproduce?

@timofeevmd

**Comment by mversic** [comment] 2023-05-04 04:39
duplicate of #3311

**Closed** 2023-05-04 04:48 UTC
Labels: Bug, iroha2
