### ISSUE TITLE
[suggestion] Consider Semantic PRs

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#4222] opened 2024-01-20 12:59 UTC
### Feature request

The semantic PR action can help with asking outside contributors to conform to a specific set of requirements. 

### Motivation

the workflow in question is 

https://github.com/Ezard/semantic-prs

### Who can help?

@mversic @BAStos525

**Comment by mversic** [comment] 2024-04-24 09:58
duplicate of #4502

**Comment by nxsaken** [comment] 2024-05-01 06:36
Superseded by #4502.

**Closed by nxsaken** 2024-05-01 06:36 UTC
Labels: Enhancement, iroha2, CI
