### ISSUE TITLE
Query sorting support for pagination

### ISSUE THREAD

**Issue by gv-timur** [hyperledger/iroha#2290] opened 2022-05-30 09:44 UTC
Add support for sorting query results in Iroha2 before applying pagination (start, limit).
For example add multiple assets of type "AssetValueType.Store" and then query top 5 sorted by some value in Metadata.

**Comment by appetrosyan** [comment] 2022-07-25 11:29
This is very likely going to be a wontfix. 

Server side  sorting for all queries is very likely to cause major abuse from users. 

Best we can do is allow sorting in middleware that communicates with an Iroha peer.

**Comment by pesterev** [comment] 2022-07-26 19:40
That looks like a duplicate of #2501.

**Comment by pesterev** [comment] 2022-07-26 19:58
@appetrosyan I suggested a decision some time ago. This is based on sorting assets by timestamps in a b-tree map. It seems your suggestion would force the sorting of assets on every request.

**Comment by appetrosyan** [comment] 2022-07-28 08:47
So the approach that you propose is going to more than double the size of a structure that is already going to account for 80% of all traffic inside a block. We've had to go to extreme lengths to reduce the size previously.

**Comment by pesterev** [comment] 2022-07-30 19:23
it will be resolved here (#2553).

**Closed** 2022-08-17 08:09 UTC
Labels: iroha2
