### ISSUE TITLE
Replay attack

### ISSUE THREAD

**Issue by victordrobny** [hyperledger/iroha#1062] opened 2018-03-09 22:16 UTC
Replay attack(or double spend attack)

Replay attack appears in any communicational system in general and in blockchain frameworks specifically. Most of the messages are sent through insecure channels. The first problem that appears in this situation is the identification of the author of the message. 

However even if the message is signed(and you are sure that raw message data was generated by the identified user), you need to be sure who initiates the broadcast of the message. Due to insecureness of the communicational channels in most scenarios, transmitted data can be sniffed and can be sent once more. In this case receiver will take two identical messages.

For cryptocurrencies, replay attack is one of the main issues. If transaction with transfer from A to B will be repeated by fraudster in blockchain system without double spend protection A will spend twice more money than he wanted.

Here are some solutions:

Bitcoin(UTXO)

In bitcoin users owns a bunch of coins. Any coin couldn’t be spent partially. Each coin in bitcoin can be either be transferred to another account entirely or can be spent in order to create new coins. So if someone wants to spend some amount of bitcoins he needs to create a coin with appropriate value first. 

Each transaction in bitcoin has input coins and output count. Each coin in the system can be in the input and output only once. These restrictions guarantee that coin will be spent only once and all other transactions with encountered input will be treated as invalid. So the double spend attack protection is sewn in the system by design.

However, this approach is not applicable in account-based systems. Since Iroha has only the quantity of the asset it is quite hard to rework model to use this approach.

Nonce

Another common approach is the nonce usage. Nonce is a number that can be used only once. It prevents transaction payload to be the same. Each time that user creates new transaction somehow takes new nonce. It leads to different hashes/signs to identical transactions. Two identical transactions with equal nonce will never be applied to the ledger.

The simplest way to generate nonce is to take a random number(string, whatever) every time. This approach is used in hyperledger sawtooth and fabric(for anonymous transactions). The disadvantage of this method is that already used nonces should be stored in order to verify the uniqueness of the new ones. To avoid storing large amounts of hashes, validity periods of transaction certificates are limited. In particular validators maintain an updated record of received transactions' hashes within the current or future validity period.

Another method that allows ensuring the uniqueness of transaction is to maintain the sequence of the nonces so the validators are able to determine whether value was used without storing it. Usually, the sequence of nonces are generated by the recurrent formula: 
nonce<sub>i</sub> = f(nonce<sub>i-1</sub>). It allows to not to remember all of the nonces that were used before. For example, Ethereum uses consecutive numbers in order to make nonces. Each account uses their own counter for transactions. So the first nonce for a particular user is 1, next is 2 and so on. Nonces are not unique in this scenario, however (nonce, account) is unique. It guarantees the uniqueness of the hash of the transactions.

The other common approach is to use some hash function in order to get new nonce. It is used in hyperledger fabric. The fabrics mechanism is quite complicated and depends on the type of the transaction(they use different types of certificates), but in general idea it the following: 
for transactions with enrollment certificate: get first nonce (for example from genesis block), nonce<sub>next</sub> = hash(nonce<sub>prev</sub>).

**Comment by l4l** [comment] 2018-03-10 12:25
Agree, that there is only one applicable way of solving the issue is nonces. But I don't really sure that we need to consider it in design schema. My opinion it's better delegate to transport (e.g TLS [has such protection](https://tools.ietf.org/html/rfc4346#appendix-F.2)), and non-secure transport implies that there is no protection against replay attacks.

**Comment by Warchant** [comment] 2018-03-10 14:56
>Reply attack

Replay attack...

**Comment by Warchant** [comment] 2018-03-10 15:01
As I mentioned before (https://soramitsu.atlassian.net/browse/IR-802) it is not a question, if it is TLS or not, TLS protects from listening the channel between client and peer, but peer can replay this transaction by himself, as many times as neede. As I mentioned before, **every account MUST have a number, which is unique for every transaction it sends**. The simplest way to implement it is a counter. Ethereum implements this approach.

*How to retrieve counter?*
As full node (peer) you already have it, it is stored in current WSV.
As light node (client) you don't have neigher blocks or current state. You **must** query this number. You **will not be able to send transactions** without knowledge of this number. System should not process transactions with the same counters from the same accounts, it must consider such transaction as single replayed transaction.

**Comment by Warchant** [comment] 2018-03-10 15:55
The consequence of not using counter is the ability of anyone who intercepts valid transaction, within a stateless validation timeframe to send this transaction many times, until (if it is asset transfer) souce account will run out of assets.

**Comment by takemiyamakoto** [comment] 2018-03-11 09:37
It can also be possible to prevent replay attacks by using timestamps. We can just require that all transactions from the same account must have a unique timestamp. If users need to send many transactions at once, we can introduce the concept of a transaction batch.

**Comment by Warchant** [comment] 2018-03-11 16:32
>must have a unique timestamp

Then you should store timestamp of last processed transaction in the account state. Then, timestamp of currently processed transaction should be strictly greater than timestamp from account state.


> If users need to send many transactions at once, we can introduce the concept of a transaction batch.

Commands from different transactions can be combined in a single transaction, so we already have it.

**Comment by neewy** [comment] 2018-03-14 06:16
Not exactly. 

As a user, I can create a batch of transactions where they all will be validated and committed together, or not at all; all or nothing **(order matters).** Banks doing batching, exchange of assets can use this schema. So, the validation of batch differs from individual transactions. Unfortunately, this requirement is not elaborated now, and we need to plan it, maybe for exchange functionality.

**Comment by neewy** [comment] 2018-03-20 14:31
So, just the timestamp is enough, right? 

If people want to send the same amount to the same address at the same time, this is a spam attack, so preventing that is a great way to do spam protection + replay attack protection at the same time (this is what @takemiyamakoto says).

@muratovv are there any implications for MST, can we just use tx counter and change validation?

**Comment by neewy** [comment] 2018-03-20 14:32
Or overall, are there any problems to use just a timestamp?

**Comment by victordrobny** [comment] 2018-03-20 14:35
The problem with MST is that you never know when transaction will be sent to ordering gate and in what order. That is why this approach with nonce sequences(or timestamps) doesn't work with mst.

**Comment by victordrobny** [comment] 2018-03-21 08:25
In order to MST transaction to go to ordering gate it needs to get some amount of signatures(quorum). Each user that signs mst transaction only by his public key. Then he sends it to some node. Each node has a pool of mst transactions and once in awhile node shares mst transactions that it has with two random neighbors. When some node gets all of the signed copies of transaction it sends it to the ordering gate.
Due to the mechanism of mst propogation and the fact that users can sign it asynchronously system can not know in what order user have signed his transactions. 
The benefit behind the idea of tx_counter and timestamp is simplisity of nonce uniquness check procedure. If nonce is bigger than previous one you sure that it is unique, but in case of multisig transactions can appear in different order. That is why nether tx counter nor timestamp is aplicable solution for mst.

**Comment by l4l** [comment] 2018-03-21 08:40
@victordrobny actually both cases are applicable to mst
It consider new signature on the tx iff hashes are equals. That implies that the second signatory must now in advance stuff like time/nonce and sign exactly same tx.
MST component actually send **only 1** tx with necessary signatures (and to the tx processor, not ordering service)

@neewy It might be issues with timestamp synchronization. So it basically become similar to the nonces: you need to ask it, to make sure that tx doesn't go to nowhere. And as long as clock as physically different you need to do it regularly

**Comment by neewy** [comment] 2018-03-21 12:23
What if we will just use random nonce?

**Comment by Warchant** [comment] 2018-03-21 16:44
Time [can be different](https://en.wikipedia.org/wiki/Clock_synchronization) on a different computers in a distributed system, moreover **it *will* be different**.
This is the only downside of using timestamps.

@neewy if you use random nonce, then:
1. you need to store all processed nonces in account state -- just ask yourself, how to check that tx is replayed when it contains random number in "Nonce" field?
2. how does client/peer determine next nonce?

As I mentioned before, every transaction for every account needs to have a unique number to prevent a replay.

**Comment by takemiyamakoto** [comment] 2018-03-22 03:31
Time is fine. The tx contents and time stamp have to be unique and this is a feature. No one should be sending the same tx at the same time to the same person for the same amount. There’s just no use case for that besides attacking the network.

**Comment by Warchant** [comment] 2018-03-22 08:59
>The tx contents and time stamp have to be unique and this is a feature.

What if user has 2 devices, device A has time 12:01, device B has time 11:59. User sends a transaction from the device A and in 1 minute sends a different transaction from the device B, so that

- tx1 has signing time 12:01
- tx2 has signing time 12:00, but sent after tx1

Tx1 gets processed and time 12:01 is stored in account's state. 

To prevent replay attacks peers need to process only transactions, which have timestamp greater than stored in account's state. Otherwise, you would need to store all timestamps (how do you check that timestamp is unique?), or query all user transactions (which is much slower, than integer comparison).

With this scheme next transaction with time 12:00 will not be processed -- it will be marked as "replayed". 

To prevent this, there should be some universal time for the distributed system, which is synchronized across all peers/clients. But, if you think, from the client prospective of view, this mechanism is not different at all from the fetching number (counter) from the blockchain.

**Comment by l4l** [comment] 2018-03-27 20:02
So what's the final decision? Leave nonce&timer as it was before?

**Comment by takemiyamakoto** [comment] 2018-03-28 05:09
@Warchant Ordering in a distributed ledger is not determined by time or some counter. Instead it is determined by the orderer and consensus mechanism. Replay protection should not even try to prevent different transactions from being sent at the same time or try to make guarantees about the order of transactions being accepted by the network.

To prevent transactions that are rejected from being arbitrarily sent back to the network later on, every transaction should have an expiration time, after which it is no longer valid. For replay protection, it is enough to guarantee that the contents of the tx (sender, receiver, amount, and time) are unique.

**Comment by Warchant** [comment] 2018-03-29 09:33
>For replay protection, it is enough to guarantee that the contents of the tx (sender, receiver, amount, and time) are unique.

How would you check that timestamp of tx that is being processed is unique? 

Naive algorithm is to search for all txs of current sender and then get all timestamps, then compare current timestamp with queried from blockchain. But this is very very slow -- O(n) , n - number of transactions in blockchain.

**Comment by takemiyamakoto** [comment] 2018-03-30 01:55
Why do you care if the tx's timestamp is unique? All you care about is that all txs are unique (unique sender, receiver, amount, and time). This is just an O(1) lookup in a global map to see if there is another tx with the same bytes in the blockchain.

**Comment by lebdron** [comment] 2018-04-05 13:40
@takemiyamakoto The solution with lookup in global map is suitable at the moment, because we already store all transaction hashes of each user in PostgreSQL, so the lookup is trivial.

**Closed by lebdron** 2018-04-05 13:40 UTC
Labels: discussion, rfc
