### ISSUE TITLE
[refactor]: Shallow objects in `data_model`

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#3921] opened 2023-09-25 11:42 UTC
Currently objects in `data_model` are nested. `Domain`s contain `Account`s and `AssetDefinition`s inside it, `Account`s contains `Asset`s and `Role`s and so on.

We should consider making objects shallow: so that all `Asset`s would be sotred in the single place and only reference owner `Account` by it's `AccountId`.

This way iteration over objects will be more effective. 

As a sidenote such structure more closely resemble data organization typically encountered in relational databases.

**Comment by mversic** [comment] 2023-10-19 10:44
let's consider after new wsv

**Comment by SamHSmith** [comment] 2024-06-27 20:22
First PR was merged.

**Comment by nxsaken** [comment] 2024-07-02 08:42
Apparently, we're moving to a sort of static Entity-Component-System / Struct of Arrays, so all data model structs should eventually disappear.

**Comment by SamHSmith** [comment] 2024-08-06 16:27
This issue is about how the code should be structured. PR's containing these changes have been merged already. Therefore the issue is closed.

**Closed by SamHSmith** 2024-08-06 16:27 UTC
Labels: question, iroha2-dev, Refactor
