### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by big-fish0** [hyperledger/iroha#1554] opened 2018-07-11 09:11 UTC
Follow is my UnsignedTx .This is ok on the last version.But the latest version logs that `Simulator stateful validation error: could not validate command with index 1: TransferAsset: is valid command validation failed: not enough balance on account 15527304517@sun-0555; transfer amount 10.00, balance 5.01` It seems that,Iroha deal the transfer first,then deal the addAssetqty.Is this a Bug?
```
 public UnsignedTx cmdAddAssetQuantity2other(String creator, String accountId, String assetName, String amount, String destAccId, String description) {
        return m_txBuilder.creatorAccountId(creator)
            .createdTime(BigInteger.valueOf( System.currentTimeMillis() ))
            .addAssetQuantity(accountId, assetName, amount)
            .transferAsset(accountId, destAccId, assetName, description, amount)
            .build();
    }
```

**Comment by muratovv** [comment] 2018-07-13 08:09
Hello,
Can you provide the genesis block and the target transaction? We have to reproduce the situation and confirm (and fix) the bug. Also, pls, specify the revision of the code.

Thank you for interest in Iroha project. Iroha's team appreciates your efforts.

**Comment by big-fish0** [comment] 2018-07-13 08:43
@muratovv 
genesis.block
```
{
   "payload":{
      "transactions":[
         {
            "payload":{
               "commands":[
                  {
                     "addPeer":{
                        "peer":{
                           "address":"localhost:10001",
                           "peerKey":"0E2icbV/5jQmrh3Jf2lSEEA3QR/PTztzncIX9F5fyZs="
                        }
                     }
                  },
                  {
                     "createRole":{
                        "roleName":"admin",
                        "permissions":[
                           "can_add_peer",
                           "can_add_signatory",
                           "can_create_account",
                           "can_create_domain",
                           "can_get_all_acc_ast",
                           "can_get_all_acc_ast_txs",
                           "can_get_all_acc_detail",
                           "can_get_all_acc_txs",
                           "can_get_all_accounts",
                           "can_get_all_signatories",
                           "can_get_all_txs",
                           "can_get_roles",
                           "can_read_assets",
                           "can_remove_signatory",
                           "can_set_quorum",
                           "can_get_blocks",
                           "can_subtract_asset_qty"
                        ]
                     }
                  },
                  {
                     "createRole":{
                        "roleName":"user",
                        "permissions":[
                           "can_add_signatory",
                           "can_get_my_acc_ast",
                           "can_get_my_acc_ast_txs",
                           "can_get_my_acc_detail",
                           "can_get_my_acc_txs",
                           "can_get_my_account",
                           "can_get_my_signatories",
                           "can_get_my_txs",
                           "can_grant_can_add_my_signatory",
                           "can_grant_can_remove_my_signatory",
                           "can_grant_can_set_my_account_detail",
                           "can_grant_can_set_my_quorum",
                           "can_grant_can_transfer_my_assets",
                           "can_receive",
                           "can_remove_signatory",
                           "can_set_quorum",
                           "can_transfer",
                           "can_add_asset_qty",
                           "can_create_asset",
                           "can_subtract_asset_qty"
                        ]
                     }
                  },
                  {
                     "createRole":{
                        "roleName":"money_creator",
                        "permissions":[
                           "can_add_asset_qty",
                           "can_create_asset",
                           "can_receive",
                           "can_transfer"
                        ]
                     }
                  },
                  {
                     "createDomain":{
                        "domainId":"test",
                        "defaultRole":"user"
                     }
                  },
		  {
                     "createDomain":{
                        "domainId":"sun",
                        "defaultRole":"user"
                     }
                  },

                  {
                     "createDomain":{
                        "domainId":"sun-0555",
                        "defaultRole":"user"
                     }
                  },

                  {
                     "createAsset":{
                        "assetName":"coin",
                        "domainId":"test",
                        "precision":2
                     }
                  },
                  {
                     "createAccount":{
                        "accountName":"admin",
                        "domainId":"test",
                        "mainPubkey":"iJ9riB4zG+IUh9t33PMsX409XoBm540v6sQjn+kdQW8="
                     }
                  },
                  {
                     "createAccount":{
                        "accountName":"test",
                        "domainId":"test",
                        "mainPubkey":"3MfszkSPLhkKSBrsfKIe5S7aVG5mC0gg9JdtATIVcJc="
                     }
                  },
                  {
                     "appendRole":{
                        "accountId":"admin@test",
                        "roleName":"admin"
                     }
                  },
                  {
                     "appendRole":{
                        "accountId":"admin@test",
                        "roleName":"money_creator"
                     }
                  }
               ]
            }
         }
      ],
      "txNumber":1,
      "height":"1",
      "prevBlockHash":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
   }
}

```

**Comment by l4l** [comment] 2018-07-13 10:20
> transfer amount 10.00

> .transferAsset("admin@test", "test@test", "coin#test", description, "1.00")

Some inconsistency here. Could you please double check the code? And if you're sure about its correctness please share the source and the binary blob of your transaction:
- `new ModelProtoTransaction(<your_unsigned_tx>).signAndAddSignature(keys).finish()`;
- then print it in hex.

I just checked that there's no bug in Iroha itself, though it still can be bug somewhere at bindings, but that's require quite some time for investigation

**Comment by big-fish0** [comment] 2018-07-13 10:32
@l4l 
If admin@test's coin#test balance is 10.00,and My tarfet transaction is 
```
m_txBuilder.creatorAccountId("admin@test")
            .createdTime(BigInteger.valueOf( System.currentTimeMillis() ))
            .addAssetQuantity(@"admin@test", "coin#test", "11.00")
            .transferAsset("admin@test", "test@test", "coin#test", description, "11.00")
            .build();
```
That's failed.

But  My tarfet transaction is 
```
m_txBuilder.creatorAccountId("admin@test")
            .createdTime(BigInteger.valueOf( System.currentTimeMillis() ))
            .addAssetQuantity(@"admin@test", "coin#test", "9.00")
            .transferAsset("admin@test", "test@test", "coin#test", description, ".00")
            .build();
```
It's ok

**Comment by l4l** [comment] 2018-07-17 10:40
Since the #1555 merged there's lot of things changed. Could you please retry this transaction? I'm still not able to verify it

**Comment by l4l** [comment] 2018-08-29 12:09
Since there's no response for more than a month I'm closing the issue. Feel free to add something, if the same issue is still present

**Closed by l4l** 2018-08-29 12:09 UTC
Labels: awaiting-response, command, needs-reproduction
